using MongoDB.Bson;using MongoDB.Bson.Serialization.Attributes;using System.ComponentModel.DataAnnotations;
namespace AILearnAPI.Api.Features.NotesRecall;
public sealed class RecallConcept{public string Concept{get;set;}="";public string Definition{get;set;}="";public List<string> Keywords{get;set;}=[];public List<string> CommonMistakes{get;set;}=[];public string RealWorldExample{get;set;}="";}
public sealed class RecallQuestion{public string Id{get;set;}=Guid.NewGuid().ToString("N");public string Question{get;set;}="";public string QuestionType{get;set;}="definition";public string Difficulty{get;set;}="intermediate";public List<string> ExpectedPoints{get;set;}=[];public List<string> ExpectedKeywords{get;set;}=[];public List<string> AnswerFramework{get;set;}=[];public string IdealShortAnswer{get;set;}="";public string IdealSpokenAnswer{get;set;}="";}
public sealed class RecallFlashcard{public string Id{get;set;}=Guid.NewGuid().ToString("N");public string Front{get;set;}="";public string Back{get;set;}="";public List<string> Keywords{get;set;}=[];}
public sealed class NoteRecallContent{[BsonId,BsonRepresentation(BsonType.ObjectId)]public string Id{get;set;}=ObjectId.GenerateNewId().ToString();public string UserId{get;set;}="";public string NoteId{get;set;}="";public string ContentHash{get;set;}="";public string Title{get;set;}="";public string Summary{get;set;}="";public List<RecallConcept> KeyConcepts{get;set;}=[];public List<RecallQuestion> RecallQuestions{get;set;}=[];public List<RecallFlashcard> Flashcards{get;set;}=[];public bool NoteQualityWarning{get;set;}public string Warning{get;set;}="";public string SuggestedCorrection{get;set;}="";public DateTime GeneratedAt{get;set;}=DateTime.UtcNow;}
public sealed class CreateRecallSessionRequest{[MinLength(1),MaxLength(20)]public List<string> NoteIds{get;set;}=[];public string Mode{get;set;}="mixed";[Range(5,15)]public int DurationMinutes{get;set;}=5;public bool IncludeVoicePractice{get;set;}=true;public string Difficulty{get;set;}="intermediate";}
public sealed class NoteRecallSession{[BsonId,BsonRepresentation(BsonType.ObjectId)]public string Id{get;set;}=ObjectId.GenerateNewId().ToString();public string UserId{get;set;}="";public List<string> NoteIds{get;set;}=[];public List<RecallQuestion> Questions{get;set;}=[];public string Mode{get;set;}="mixed";public int DurationMinutes{get;set;}public int CurrentIndex{get;set;}public string Status{get;set;}="active";public DateTime StartedAt{get;set;}=DateTime.UtcNow;public DateTime? CompletedAt{get;set;}}
public sealed class RecallAnswerRequest{[Required]public string QuestionId{get;set;}="";[Required,StringLength(12000)]public string Answer{get;set;}="";[Range(0,5)]public int HintsUsed{get;set;}public bool NoteRevealed{get;set;}public int DurationSeconds{get;set;}public string IdempotencyKey{get;set;}="";}
public sealed class RecallEvaluation{public double RecallScore{get;set;}public double IndependentRecallScore{get;set;}public double TechnicalAccuracyScore{get;set;}public double CompletenessScore{get;set;}public double EnglishScore{get;set;}public List<string> RememberedPoints{get;set;}=[];public List<string> MissingPoints{get;set;}=[];public List<string> IncorrectPoints{get;set;}=[];public List<string> MatchedKeywords{get;set;}=[];public List<string> MissingKeywords{get;set;}=[];public List<string> LanguageCorrections{get;set;}=[];public string EasySpokenAnswer{get;set;}="";public bool ShouldRepeat{get;set;}public DateTime NextRevisionAt{get;set;}public string Feedback{get;set;}="";}
public sealed class NoteRecallAttempt{[BsonId,BsonRepresentation(BsonType.ObjectId)]public string Id{get;set;}=ObjectId.GenerateNewId().ToString();public string UserId{get;set;}="";public string SessionId{get;set;}="";public string QuestionId{get;set;}="";public string IdempotencyKey{get;set;}="";public string Answer{get;set;}="";public int HintsUsed{get;set;}public bool NoteRevealed{get;set;}public RecallEvaluation Evaluation{get;set;}=new();public DateTime CreatedAt{get;set;}=DateTime.UtcNow;}
public sealed class NoteRecallItem{[BsonId,BsonRepresentation(BsonType.ObjectId)]public string Id{get;set;}=ObjectId.GenerateNewId().ToString();public string UserId{get;set;}="";public string NoteId{get;set;}="";public string QuestionId{get;set;}="";public string Concept{get;set;}="";public string Question{get;set;}="";public List<string> ExpectedKeywords{get;set;}=[];public double LastRecallScore{get;set;}public double AverageRecallScore{get;set;}public int AttemptCount{get;set;}public int HintCount{get;set;}public DateTime LastAttemptAt{get;set;}public DateTime NextRevisionAt{get;set;}public int RevisionStage{get;set;}public int ConsecutiveSuccessfulAttempts{get;set;}public bool Mastered{get;set;}}
public sealed class RecallDashboard{public int DueToday{get;set;}public int WeakConcepts{get;set;}public int RecentlyMastered{get;set;}public int CurrentRecallStreak{get;set;}public double AverageRecallScore{get;set;}public double EnglishSpeakingScore{get;set;}}
