using System.Security.Cryptography;using System.Text;using System.Text.Json;using AILearnAPI.Api.Services;using AILearnAPI.Domain.Interfaces;
namespace AILearnAPI.Api.Features.NotesRecall;
public sealed class NotesRecallService{readonly NotesRecallRepository repo;readonly INoteRepository notes;readonly IOllamaService ai;static readonly JsonSerializerOptions json=new(){PropertyNameCaseInsensitive=true};public NotesRecallService(NotesRecallRepository r,INoteRepository n,IOllamaService a){repo=r;notes=n;ai=a;}
public async Task<NoteRecallContent>Generate(string user,string noteId,bool force,CancellationToken ct){var note=await notes.GetByIdAndUserIdAsync(noteId,user)??throw new KeyNotFoundException("Note not found.");var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(note.Topic+"\n"+note.Content)));var existing=await repo.Content(noteId,user);if(!force&&existing?.ContentHash==hash)return existing;var schema=JsonSerializer.Serialize(new NoteRecallContent(),json);var prompt=$"Use this user's note as the main source of truth. Return JSON only matching {schema}. Split headings and long documents into focused concepts. Generate 5 concise recall questions and 5 flashcards. Accept semantic wording. If technically suspect set noteQualityWarning. Title: {note.Topic}. Note: {note.Content[..Math.Min(note.Content.Length,16000)]}";var raw=(await ai.GenerateAsync(prompt,temperature:.25f,maxTokens:2400,cancellationToken:ct)).Response;var x=Parse<NoteRecallContent>(raw);x.Id=existing?.Id??x.Id;x.UserId=user;x.NoteId=noteId;x.ContentHash=hash;x.Title=note.Topic;x.GeneratedAt=DateTime.UtcNow;foreach(var q in x.RecallQuestions)if(string.IsNullOrWhiteSpace(q.Id))q.Id=Guid.NewGuid().ToString("N");await repo.SaveContent(x);return x;}
public Task<NoteRecallContent?>Get(string u,string n)=>repo.Content(n,u);
public async Task<NoteRecallSession>Create(string u,CreateRecallSessionRequest r,CancellationToken ct){var all=new List<RecallQuestion>();foreach(var id in r.NoteIds.Distinct()){var c=await Generate(u,id,false,ct);all.AddRange(c.RecallQuestions);}var mixed=all.OrderBy(_=>Guid.NewGuid()).Take(Math.Max(3,r.DurationMinutes)).ToList();return await repo.Create(new(){UserId=u,NoteIds=r.NoteIds,Mode=r.Mode,DurationMinutes=r.DurationMinutes,Questions=mixed});}
public Task<NoteRecallSession?>Session(string u,string id)=>repo.Session(id,u);
public async Task<NoteRecallAttempt>Answer(string u,string id,RecallAnswerRequest r,CancellationToken ct){if(!string.IsNullOrWhiteSpace(r.IdempotencyKey)){var old=await repo.Attempt(r.IdempotencyKey,u);if(old!=null)return old;}var s=await repo.Session(id,u)??throw new KeyNotFoundException("Recall session not found.");var q=s.Questions.FirstOrDefault(x=>x.Id==r.QuestionId)??throw new KeyNotFoundException("Recall question not found.");var schema=JsonSerializer.Serialize(new RecallEvaluation(),json);var prompt=$"Evaluate semantic recall using expected points and keywords, not exact wording. Return JSON only matching {schema}. Scores 0-10. Reduce independentRecallScore gently for {r.HintsUsed} hints and noteRevealed={r.NoteRevealed}. Question: {q.Question}. Expected points: {string.Join("; ",q.ExpectedPoints)}. Keywords: {string.Join(", ",q.ExpectedKeywords)}. Ideal: {q.IdealSpokenAnswer}. User answer: {r.Answer}";var raw=(await ai.GenerateAsync(prompt,temperature:.15f,maxTokens:1000,cancellationToken:ct)).Response;var e=Parse<RecallEvaluation>(raw);e.RecallScore=Math.Clamp(e.RecallScore,0,10);e.IndependentRecallScore=Math.Clamp(e.RecallScore-r.HintsUsed*.5-(r.NoteRevealed?1:0),0,10);var days=e.RecallScore<4?1:e.RecallScore<7?1:e.RecallScore<9?3:7;e.NextRevisionAt=DateTime.UtcNow.AddDays(days);e.ShouldRepeat=e.RecallScore<7;var attempt=await repo.Add(new(){UserId=u,SessionId=id,QuestionId=q.Id,IdempotencyKey=r.IdempotencyKey,Answer=r.Answer,HintsUsed=r.HintsUsed,NoteRevealed=r.NoteRevealed,Evaluation=e});await repo.Upsert(new(){UserId=u,NoteId=s.NoteIds.FirstOrDefault()??"",QuestionId=q.Id,Concept=q.Question,Question=q.Question,ExpectedKeywords=q.ExpectedKeywords,LastRecallScore=e.RecallScore,AverageRecallScore=e.RecallScore,AttemptCount=1,HintCount=r.HintsUsed,LastAttemptAt=DateTime.UtcNow,NextRevisionAt=e.NextRevisionAt,ConsecutiveSuccessfulAttempts=e.RecallScore>=8?1:0});s.CurrentIndex=Math.Min(s.Questions.Count,s.CurrentIndex+1);await repo.Update(s);return attempt;}
public async Task<RecallDashboard>Dashboard(string u){var all=await repo.All(u);return new(){DueToday=all.Count(x=>!x.Mastered&&x.NextRevisionAt<=DateTime.UtcNow),WeakConcepts=all.Count(x=>x.AverageRecallScore<6),RecentlyMastered=all.Count(x=>x.Mastered&&x.LastAttemptAt>=DateTime.UtcNow.AddDays(-7)),AverageRecallScore=all.Count==0?0:Math.Round(all.Average(x=>x.AverageRecallScore)*10),EnglishSpeakingScore=0,CurrentRecallStreak=0};}public Task<List<NoteRecallItem>>Due(string u)=>repo.Due(u);public async Task<NoteRecallItem>Master(string u,string id,bool mastered){var x=await repo.Item(id,u)??throw new KeyNotFoundException("Recall item not found.");x.Mastered=mastered;x.NextRevisionAt=mastered?DateTime.UtcNow.AddDays(30):DateTime.UtcNow;await repo.UpdateItem(x);return x;}
static T Parse<T>(string raw){var b=raw.IndexOf('{');var e=raw.LastIndexOf('}');if(b<0||e<=b)throw new InvalidOperationException("AI returned invalid recall JSON.");return JsonSerializer.Deserialize<T>(raw[b..(e+1)],json)??throw new InvalidOperationException("AI returned empty recall JSON.");}}
