import { AdminPrepImportQuestion } from '../admin-interview-prep/admin-interview-prep.service';

export const DOTNET_CORE_QUESTION_PACK: AdminPrepImportQuestion[] = [
  { category: '.NET Core', question: 'What is .NET Core, and how is it different from the .NET Framework?', difficulty: 'Easy', tags: ['dotnet-core', 'fundamentals'], answerHint: '.NET Core is cross-platform, open source, modular, and designed for side-by-side deployment. The .NET Framework is Windows-focused and mainly maintained for existing applications.' },
  { category: '.NET Core', question: 'Explain the role of the CLR in .NET applications.', difficulty: 'Easy', tags: ['clr', 'runtime'], answerHint: 'The CLR executes managed code and provides JIT compilation, garbage collection, exception handling, type safety, and threading services.' },
  { category: '.NET Core', question: 'What is managed code and unmanaged code?', difficulty: 'Easy', tags: ['clr', 'memory'], answerHint: 'Managed code runs under the CLR and receives runtime services. Unmanaged code runs directly as native machine code outside CLR management.' },
  { category: '.NET Core', question: 'How does dependency injection work in ASP.NET Core?', difficulty: 'Medium', tags: ['dependency-injection', 'services'], answerHint: 'Services are registered in IServiceCollection and resolved from IServiceProvider. Prefer constructor injection and select an appropriate transient, scoped, or singleton lifetime.' },
  { category: '.NET Core', question: 'Explain transient, scoped, and singleton service lifetimes.', difficulty: 'Medium', tags: ['dependency-injection', 'lifetimes'], answerHint: 'Transient creates an instance per resolution, scoped creates one per request or scope, and singleton creates one for the application lifetime.' },
  { category: '.NET Core', question: 'What is middleware in ASP.NET Core?', difficulty: 'Easy', tags: ['middleware', 'request-pipeline'], answerHint: 'Middleware is a component in the HTTP pipeline that can inspect, modify, handle, or pass a request to the next component.' },
  { category: '.NET Core', question: 'Why does middleware order matter?', difficulty: 'Medium', tags: ['middleware', 'request-pipeline'], answerHint: 'Requests flow through middleware in registration order and responses return in reverse order. Incorrect ordering can bypass authentication, authorization, routing, or exception handling.' },
  { category: '.NET Core', question: 'What is the difference between Use, Run, and Map middleware?', difficulty: 'Medium', tags: ['middleware', 'pipeline'], answerHint: 'Use can call the next middleware, Run terminates the pipeline, and Map branches the pipeline based on the request path.' },
  { category: '.NET Core', question: 'How does configuration work in ASP.NET Core?', difficulty: 'Medium', tags: ['configuration', 'appsettings'], answerHint: 'Configuration combines providers such as appsettings files, environment variables, command-line arguments, user secrets, and external stores; later providers override earlier values.' },
  { category: '.NET Core', question: 'Explain the Options pattern and IOptions, IOptionsSnapshot, and IOptionsMonitor.', difficulty: 'Hard', tags: ['configuration', 'options-pattern'], answerHint: 'The Options pattern binds configuration to typed classes. IOptions is singleton-style, IOptionsSnapshot refreshes per scope, and IOptionsMonitor supports change notifications and current values.' },
  { category: '.NET Core', question: 'How do environments work in ASP.NET Core?', difficulty: 'Easy', tags: ['environments', 'configuration'], answerHint: 'DOTNET_ENVIRONMENT or ASPNETCORE_ENVIRONMENT selects an environment such as Development, Staging, or Production and can load environment-specific configuration.' },
  { category: '.NET Core', question: 'How do you implement global exception handling in ASP.NET Core?', difficulty: 'Medium', tags: ['exceptions', 'middleware'], answerHint: 'Use the built-in exception handler or custom exception-handling middleware, log the exception, and return a consistent ProblemDetails response without exposing sensitive data.' },
  { category: '.NET Core', question: 'How does logging work in ASP.NET Core?', difficulty: 'Medium', tags: ['logging', 'observability'], answerHint: 'Inject ILogger<T>, use structured message templates and levels, and configure providers and filters through configuration.' },
  { category: '.NET Core', question: 'What are hosted services and BackgroundService?', difficulty: 'Medium', tags: ['hosted-services', 'background-jobs'], answerHint: 'IHostedService runs work with the application lifecycle. BackgroundService provides ExecuteAsync for long-running work and must honor cancellation and create scopes for scoped dependencies.' },
  { category: '.NET Core', question: 'What is the Generic Host in .NET?', difficulty: 'Medium', tags: ['hosting', 'generic-host'], answerHint: 'The Generic Host centralizes dependency injection, configuration, logging, application lifetime, and hosted-service management for web and non-web applications.' },
  { category: '.NET Core', question: 'What is Kestrel?', difficulty: 'Easy', tags: ['kestrel', 'hosting'], answerHint: 'Kestrel is the cross-platform web server used by ASP.NET Core. In production it can run directly or behind a reverse proxy.' },
  { category: '.NET Core', question: 'What is the difference between framework-dependent and self-contained deployment?', difficulty: 'Medium', tags: ['deployment', 'runtime'], answerHint: 'Framework-dependent deployment requires a compatible installed runtime and is smaller. Self-contained deployment includes the runtime and is larger but independent of machine installation.' },
  { category: '.NET Core', question: 'What are global tools and local tools in the .NET CLI?', difficulty: 'Easy', tags: ['dotnet-cli', 'tools'], answerHint: 'Global tools are available for a user or machine. Local tools are recorded in a tool manifest, making versions reproducible for a repository.' },
  { category: '.NET Core', question: 'How does garbage collection work in .NET?', difficulty: 'Hard', tags: ['garbage-collection', 'memory'], answerHint: 'The generational GC automatically reclaims unreachable managed objects. Generations 0, 1, and 2 optimize collection frequency; IDisposable is still required for deterministic cleanup of unmanaged resources.' },
  { category: '.NET Core', question: 'What is the difference between IDisposable and a finalizer?', difficulty: 'Medium', tags: ['idisposable', 'memory'], answerHint: 'IDisposable provides deterministic cleanup through Dispose or using. A finalizer is a nondeterministic fallback for directly owned unmanaged resources and adds GC cost.' },
  { category: '.NET Core', question: 'How should async and await be used in ASP.NET Core?', difficulty: 'Medium', tags: ['async-await', 'performance'], answerHint: 'Use async APIs for I/O, await the task, propagate cancellation, avoid blocking with Result or Wait, and avoid unnecessary Task.Run for request work.' },
  { category: '.NET Core', question: 'What is IHttpClientFactory and why should you use it?', difficulty: 'Medium', tags: ['httpclientfactory', 'resilience'], answerHint: 'IHttpClientFactory centralizes client configuration, manages handler lifetimes to avoid socket exhaustion, and supports named, typed, generated, and resilient clients.' },
  { category: '.NET Core', question: 'How do model binding and validation work in ASP.NET Core?', difficulty: 'Medium', tags: ['model-binding', 'validation'], answerHint: 'Model binding maps route, query, form, header, and body values to parameters or models. Validation applies configured rules or attributes and API controllers can automatically return validation errors.' },
  { category: '.NET Core', question: 'What are Minimal APIs, and when would you use them?', difficulty: 'Medium', tags: ['minimal-api', 'web-api'], answerHint: 'Minimal APIs define HTTP endpoints with a lightweight routing syntax. They suit small services and focused APIs while still supporting DI, filters, validation, and OpenAPI.' },
  { category: '.NET Core', question: 'How do you improve the performance of an ASP.NET Core application?', difficulty: 'Hard', tags: ['performance', 'scalability'], answerHint: 'Measure first, use async I/O, cache suitable data, paginate queries, reduce allocations and serialization, optimize database access, enable compression, and monitor production metrics.' }
];
