import { AdminPrepImportQuestion } from '../admin-interview-prep/admin-interview-prep.service';

export const SQL_QUESTION_PACK: AdminPrepImportQuestion[] = [
  { category: 'SQL', question: 'What is the difference between INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN?', difficulty: 'Easy', tags: ['joins'], answerHint: 'Explain which unmatched rows each join preserves and give a small two-table example.' },
  { category: 'SQL', question: 'How do ROW_NUMBER, RANK, and DENSE_RANK differ?', difficulty: 'Medium', tags: ['window-functions', 'ranking'], answerHint: 'Compare their behavior when ORDER BY values tie: unique sequence, skipped ranks, and consecutive ranks.' },
  { category: 'SQL', question: 'What is a CTE, and when would you use a recursive CTE?', difficulty: 'Medium', tags: ['cte', 'recursion'], answerHint: 'A CTE names a query result for one statement; recursion is useful for trees, hierarchies, and graph-like traversal.' },
  { category: 'SQL', question: 'How do clustered and nonclustered indexes differ?', difficulty: 'Medium', tags: ['indexes', 'performance'], answerHint: 'Discuss physical row order, leaf pages, lookup cost, and why a table can have only one clustered index.' },
  { category: 'SQL', question: 'How would you diagnose and optimize a slow SQL query?', difficulty: 'Hard', tags: ['performance', 'execution-plan'], answerHint: 'Start with the actual execution plan and runtime metrics; check scans, estimates, joins, indexes, predicates, spills, and blocking.' },
  { category: 'SQL', question: 'What makes a query predicate non-SARGable?', difficulty: 'Hard', tags: ['sargability', 'indexes'], answerHint: 'Functions or implicit conversions on indexed columns can prevent seeks; rewrite predicates to compare the raw column to a range or compatible value.' },
  { category: 'SQL', question: 'What are ACID properties in a relational database?', difficulty: 'Easy', tags: ['transactions', 'acid'], answerHint: 'Define atomicity, consistency, isolation, and durability with a transaction-oriented example.' },
  { category: 'SQL', question: 'Explain transaction isolation levels and common concurrency anomalies.', difficulty: 'Hard', tags: ['transactions', 'concurrency'], answerHint: 'Cover dirty reads, non-repeatable reads, phantoms, blocking, and snapshot-based alternatives.' },
  { category: 'SQL', question: 'What causes a database deadlock, and how do you prevent it?', difficulty: 'Hard', tags: ['deadlocks', 'concurrency'], answerHint: 'Transactions acquire resources in conflicting order. Keep transactions short, use consistent access order, index well, and retry the victim.' },
  { category: 'SQL', question: 'When should you use EXISTS instead of IN or a JOIN?', difficulty: 'Medium', tags: ['exists', 'subqueries'], answerHint: 'EXISTS expresses a semi-join and can stop after the first match; discuss NULL semantics and accidental duplication from JOIN.' },
  { category: 'SQL', question: 'What is the difference between WHERE and HAVING?', difficulty: 'Easy', tags: ['filtering', 'aggregation'], answerHint: 'WHERE filters rows before grouping; HAVING filters groups after aggregation.' },
  { category: 'SQL', question: 'How do you find and safely remove duplicate rows?', difficulty: 'Medium', tags: ['duplicates', 'window-functions'], answerHint: 'Use ROW_NUMBER partitioned by the business key, verify the result, then delete rows whose sequence is greater than one inside a transaction.' },
  { category: 'SQL', question: 'What is database normalization, and when is denormalization justified?', difficulty: 'Medium', tags: ['normalization', 'design'], answerHint: 'Explain 1NF through 3NF, update anomalies, and deliberate denormalization for measured read performance or reporting needs.' },
  { category: 'SQL', question: 'What is parameter sniffing and how can it affect query performance?', difficulty: 'Hard', tags: ['parameter-sniffing', 'execution-plan'], answerHint: 'A cached plan optimized for one parameter distribution can perform poorly for another; discuss statistics, recompilation, and query-store-guided fixes.' },
  { category: 'SQL', question: 'How does keyset pagination differ from OFFSET pagination?', difficulty: 'Hard', tags: ['pagination', 'performance'], answerHint: 'OFFSET work grows with page depth; keyset pagination seeks after the last stable sort key and scales better.' },
  { category: 'SQL', question: 'What is the difference between DELETE, TRUNCATE, and DROP?', difficulty: 'Easy', tags: ['ddl', 'dml'], answerHint: 'Compare row filtering, logging, identity behavior, triggers, object removal, locking, and transaction support for the target database.' },
  { category: 'SQL', question: 'How do window functions differ from GROUP BY?', difficulty: 'Medium', tags: ['window-functions', 'aggregation'], answerHint: 'GROUP BY collapses rows; window functions calculate across a related set while retaining row-level detail.' },
  { category: 'SQL', question: 'How would you model and query a many-to-many relationship?', difficulty: 'Medium', tags: ['relationships', 'schema-design'], answerHint: 'Use a junction table with both foreign keys, an appropriate composite unique key, and indexes that support access from either side.' },
  { category: 'SQL', question: 'What information do you look for in a SQL execution plan?', difficulty: 'Hard', tags: ['execution-plan', 'performance'], answerHint: 'Review access methods, join algorithms, row estimates versus actuals, warnings, sorts, spills, key lookups, and the highest-cost operators.' },
  { category: 'SQL', question: 'How should NULL values be handled in comparisons and aggregates?', difficulty: 'Medium', tags: ['null', 'aggregates'], answerHint: 'Use IS NULL, understand three-valued logic, note that most aggregates ignore NULL, and avoid NOT IN when the subquery can return NULL.' }
];
