import { Injectable } from '@angular/core'; import { HttpClient } from '@angular/common/http'; import { Observable } from 'rxjs'; import { environment } from '../../../environments/environment';
import { BattleAnswer,BattleHistoryDetail,BattleQuestion,BattleSession,BattleSetup,BattleSummary,EnglishMistake,RetryComparison,RevisionItem } from '../interview-battle.models';
@Injectable({providedIn:'root'}) export class InterviewBattleService { private readonly url=`${environment.apiUrl}/interview-battle`; constructor(private http:HttpClient){}
createSession(x:BattleSetup):Observable<BattleSession>{return this.http.post<BattleSession>(`${this.url}/sessions`,x);} nextQuestion(id:string):Observable<BattleQuestion>{return this.http.post<BattleQuestion>(`${this.url}/sessions/${id}/question`,{});} submit(id:string,questionId:string,userTranscript:string,answerDurationSeconds:number,startedSpeakingAfterSeconds:number):Observable<BattleAnswer>{return this.http.post<BattleAnswer>(`${this.url}/sessions/${id}/answers`,{questionId,userTranscript,answerDurationSeconds,startedSpeakingAfterSeconds});} complete(id:string):Observable<BattleSummary>{return this.http.post<BattleSummary>(`${this.url}/sessions/${id}/complete`,{});}
retry(id:string,answerId:string,userTranscript:string,answerDurationSeconds:number,startedSpeakingAfterSeconds:number):Observable<RetryComparison>{return this.http.post<RetryComparison>(`${this.url}/sessions/${id}/answers/${answerId}/retry`,{questionId:'',userTranscript,answerDurationSeconds,startedSpeakingAfterSeconds});}
followUp(id:string,answerId:string):Observable<BattleQuestion>{return this.http.post<BattleQuestion>(`${this.url}/sessions/${id}/answers/${answerId}/follow-up`,{});}
history():Observable<BattleSession[]>{return this.http.get<BattleSession[]>(`${this.url}/history`);} historyDetail(id:string):Observable<BattleHistoryDetail>{return this.http.get<BattleHistoryDetail>(`${this.url}/history/${id}`);}
revision():Observable<RevisionItem[]>{return this.http.get<RevisionItem[]>(`${this.url}/revision`);} revisionAttempt(id:string,technicalScore:number,englishScore:number):Observable<RevisionItem>{return this.http.post<RevisionItem>(`${this.url}/revision/${id}/attempt`,{technicalScore,englishScore});}
mistakes(type?:string):Observable<EnglishMistake[]>{return this.http.get<EnglishMistake[]>(`${this.url}/english-mistakes`,{params:type?{type}:{}});} markMistake(id:string,mastered:boolean):Observable<EnglishMistake>{return this.http.patch<EnglishMistake>(`${this.url}/english-mistakes/${id}/mastered`,mastered);}
}
