import { Injectable,NgZone } from '@angular/core'; import { BehaviorSubject } from 'rxjs';
declare global { interface Window { webkitSpeechRecognition:any; SpeechRecognition:any; } }
@Injectable({providedIn:'root'}) export class SpeechRecognitionService { readonly transcript$=new BehaviorSubject<string>(''); readonly recording$=new BehaviorSubject(false); readonly error$=new BehaviorSubject<string>(''); private recognition:any; private started=0; private keepListening=false; private finalText='';
constructor(private zone:NgZone){} get supported(){return !!(window.SpeechRecognition||window.webkitSpeechRecognition);} get durationSeconds(){return this.started?Math.round((Date.now()-this.started)/1000):0;}
start(initial=''){if(this.recording$.value)return;if(!this.supported){this.error$.next('Speech recognition is not supported here. You can type your answer instead.');return;}this.keepListening=true;this.finalText=initial;this.started=Date.now();this.error$.next('');this.beginRecognition();}
stop(){this.keepListening=false;if(this.recognition){try{this.recognition.stop();}catch{}}this.recognition=undefined;this.recording$.next(false);}
reset(){this.stop();this.started=0;this.finalText='';this.transcript$.next('');this.error$.next('');}
private beginRecognition(){if(!this.keepListening)return;const C=window.SpeechRecognition||window.webkitSpeechRecognition;const recognition=new C();this.recognition=recognition;recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-US';recognition.onresult=(e:any)=>this.zone.run(()=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)this.finalText+=`${text} `;else interim+=text;}this.transcript$.next((this.finalText+interim).trim());});recognition.onerror=(e:any)=>this.zone.run(()=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){this.keepListening=false;this.error$.next('Microphone permission was denied. Allow microphone access or type your answer.');}else if(e.error!=='no-speech'&&e.error!=='aborted'){this.error$.next(`Microphone error: ${e.error}. You can continue typing.`);}});recognition.onend=()=>this.zone.run(()=>{if(this.keepListening){setTimeout(()=>this.beginRecognition(),150);}else this.recording$.next(false);});try{recognition.start();this.recording$.next(true);}catch{this.keepListening=false;this.recording$.next(false);this.error$.next('The microphone could not start. You can continue typing your answer.');}}
}
