export interface BattleSetup { role:string; experienceLevel:string; technologies:string[]; interviewType:string; difficulty:string; interviewerStyle:string; durationMinutes:number; assistanceLevel:string; plannedQuestion?:string; plannedQuestionCategory?:string; plannedAnswerHint?:string; sourceQuestionId?:string; sourceNoteId?:string; }
export interface BattleSession extends BattleSetup { id:string; status:string; currentQuestionIndex:number; startedAt:string; completedAt?:string; overallScore:number; technicalScore:number; englishScore:number; confidenceScore:number; answerStructureScore:number; }
export interface BattleQuestion { id:string; question:string; questionType:string; answerFramework:string[]; technology:string; sequence:number; }
export interface TechnicalEvaluation { score:number; correctPoints:string[]; missingPoints:string[]; incorrectPoints:string[]; depthScore:number; seniorityScore:number; feedback:string; }
export interface CommunicationEvaluation { overallScore:number; grammarScore:number; clarityScore:number; fluencyScore:number; confidenceScore:number; professionalVocabularyScore:number; fillerWords:{word:string;count:number}[]; uncertainPhrases:string[]; longPauses:string[]; feedback:string; }
export interface BattleAnswer { id:string; transcript:string; evaluation:{technicalEvaluation:TechnicalEvaluation;communicationEvaluation:CommunicationEvaluation;languageCorrections:{original:string;corrected:string;easyToSpeak:string;explanation:string}[];answerImprovement:{idealStructure:string[];startWith:string;keyPointsToInclude:string[];improvedAnswer:string;easySpokenAnswer:string;shortAnswer:string;whyThisWorks:string};followUpQuestion:string}; }
export interface BattleSummary { overallScore:number; technicalKnowledge:number; englishCommunication:number; answerStructure:number; confidence:number; seniorityDemonstration:number; averageResponseTime:number; fillerWordCount:number; questionsAnswered:number; questionsSkipped:number; strongTopics:string[]; weakTopics:string[]; recommendedNextPractice:string; }
export interface RetryComparison { firstAttempt:BattleAnswer; secondAttempt:BattleAnswer; technicalImprovement:number; englishImprovement:number; fillerWordsReduced:number; missingPointsReduced:number; }
export interface RevisionItem { id:string;topic:string;technology:string;question:string;questionType:string;missingConcepts:string[];incorrectConcepts:string[];technicalScore:number;englishScore:number;attemptCount:number;nextRevisionAt:string;revisionLevel:number;mastered:boolean; }
export interface EnglishMistake { id:string;originalSentence:string;correctedSentence:string;easyToSpeakSentence:string;mistakeType:string;explanation:string;occurrenceCount:number;lastDetectedAt:string;mastered:boolean; }
export interface BattleHistoryDetail { session:BattleSession;questions:BattleQuestion[];answers:BattleAnswer[]; }
